# Generated by Django 2.2.26 on 2022-02-01 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220201_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Designation'),
        ),
    ]
